line-length = 100
select = ["E", "F", "W", "C90", "I", "N", "D", "UP", "YTT", "ANN", "S", "BLE", "B", "A", "COM", "C4", "DTZ", "EM", "EXE", "FBT", "ICN", "INP", "PIE", "PT", "Q", "RET", "SIM", "T20", "TID", "TRY", "RUF"]
ignore = []
exclude = [".git", "__pycache__", "build", "dist", ".venv", "venv", "env", "docs", "tests/__pycache__"]
