name: Go CI

on:
  push:
    paths:
      - 'signature-builder/go/**'
  pull_request:
    paths:
      - 'signature-builder/go/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: signature-builder/go
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Lint
        run: |
          go vet ./src/...
      - name: Run tests
        run: |
          go test ./tests/...
