name: Python CI

on:
  push:
    paths:
      - 'signature-builder/python/**'
  pull_request:
    paths:
      - 'signature-builder/python/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: signature-builder/python
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with ruff
        run: |
          ruff check src tests scripts
      - name: Type check with mypy
        run: |
          mypy src
      - name: Run tests
        run: |
          python -m pytest tests
