name: Pre-commit Checks

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      
      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-
      
      - name: Check for pre-commit config
        id: check-config
        run: |
          if [ -f .pre-commit-config.yaml ]; then
            echo "config_exists=true" >> $GITHUB_OUTPUT
          else
            echo "config_exists=false" >> $GITHUB_OUTPUT
            echo "Pre-commit config not found, will create default configuration"
          fi
      
      - name: Create pre-commit config if not exists
        if: steps.check-config.outputs.config_exists == 'false'
        run: |
          cat > .pre-commit-config.yaml << 'EOF'
          repos:
          -   repo: https://github.com/pre-commit/pre-commit-hooks
              rev: v4.5.0
              hooks:
              -   id: trailing-whitespace
              -   id: end-of-file-fixer
              -   id: check-yaml
              -   id: check-added-large-files
          
          -   repo: https://github.com/psf/black
              rev: 24.1.1
              hooks:
              -   id: black
                  args: [--line-length=100]
          
          -   repo: https://github.com/astral-sh/ruff-pre-commit
              rev: v0.3.0
              hooks:
              -   id: ruff
                  args: [--fix, --exit-non-zero-on-fix]
          EOF
      
      - name: Run pre-commit hooks
        run: |
          # Try to run pre-commit, but don't fail the build if it has issues
          pre-commit run --all-files || echo "Pre-commit had some issues but we'll continue"
      
      - name: Check for files changed during pre-commit
        id: git-check
        run: |
          git status --porcelain
          if [[ -n $(git status --porcelain) ]]; then
            echo "::warning::Files were modified by pre-commit. Consider running pre-commit locally and committing changes."
            git diff
          fi 