name: Python Tests

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/python-tests.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/python-tests.yml'
  workflow_dispatch:  # Allow manual triggering

# Управление параллелизмом для предотвращения одновременных запусков
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Ограничение прав доступа GITHUB_TOKEN
permissions:
  contents: read
  checks: write  # Для публикации результатов тестов

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Проверка наличия директории setup-python-env
      - name: Check for composite action
        id: check-action
        run: |
          if [ -d ".github/actions/setup-python-env" ] && [ -f ".github/actions/setup-python-env/action.yml" ]; then
            echo "action_exists=true" >> $GITHUB_OUTPUT
            echo "✅ Композитный экшен найден"
          else
            echo "::warning::Композитный экшен не найден в .github/actions/setup-python-env, используем резервную настройку"
            echo "action_exists=false" >> $GITHUB_OUTPUT
          fi
      
      # Используем наш composite action, если он доступен
      - name: Setup Python environment using composite action
        if: steps.check-action.outputs.action_exists == 'true'
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}
          install-poetry: ${{ hashFiles('poetry.lock') != '' && 'true' || 'false' }}
          install-dev-deps: 'true'
          create-env-file: 'true'
      
      # Резервная настройка окружения, если composite action недоступен
      - name: Fallback Python setup
        if: steps.check-action.outputs.action_exists != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      # Резервная установка зависимостей, если composite action недоступен
      - name: Fallback dependencies setup
        if: steps.check-action.outputs.action_exists != 'true'
        run: |
          python -m pip install --upgrade pip
          
          # Определение метода управления зависимостями
          if [ -f poetry.lock ]; then
            echo "✅ Обнаружен poetry.lock, устанавливаем Poetry..."
            curl -sSL https://install.python-poetry.org | python3 -
            echo "$HOME/.local/bin" >> $GITHUB_PATH
            export PATH="$HOME/.local/bin:$PATH"
            
            poetry config virtualenvs.create true
            poetry config virtualenvs.in-project true
            poetry install --no-interaction
            echo "POETRY_AVAILABLE=true" >> $GITHUB_ENV
          elif [ -f requirements.txt ]; then
            echo "✅ Установка из requirements.txt..."
            pip install -r requirements.txt
            echo "POETRY_AVAILABLE=false" >> $GITHUB_ENV
          elif [ -f pyproject.toml ]; then
            echo "✅ Установка из pyproject.toml..."
            pip install .
            echo "POETRY_AVAILABLE=false" >> $GITHUB_ENV
          else
            echo "⚠️ Не найдены файлы зависимостей"
            echo "POETRY_AVAILABLE=false" >> $GITHUB_ENV
          fi
          
          # Установка инструментов для тестирования
          echo "✅ Установка инструментов для тестирования..."
          pip install pytest pytest-asyncio pytest-cov pytest-mock
          
          # Создание .env файла
          if [ -f .env.example ] && [ ! -f .env ]; then
            echo "✅ Создание .env файла из примера..."
            cp .env.example .env
          fi
          
          # Настройка PYTHONPATH
          echo "✅ Настройка PYTHONPATH..."
          echo "PYTHONPATH=$GITHUB_WORKSPACE:$PYTHONPATH" >> $GITHUB_ENV
      
      - name: Run tests with pytest
        run: |
          echo "🧪 Запуск тестов..."
          if [ "${{ env.POETRY_AVAILABLE }}" == "true" ] || [ -f poetry.lock ]; then
            poetry run python -m pytest -xvs --cov=src --cov-report=xml
          else
            python -m pytest -xvs --cov=src --cov-report=xml
          fi
        env:
          DMARKET_PUBLIC_KEY: ${{ secrets.DMARKET_PUBLIC_KEY || 'test_public_key' }}
          DMARKET_SECRET_KEY: ${{ secrets.DMARKET_SECRET_KEY || 'test_secret_key' }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN || 'test_token' }}
      
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            coverage.xml
            .coverage
            pytest-report.xml
          retention-days: 7
      
      - name: Debug info
        if: always()
        run: |
          echo "💻 Отладочная информация:"
          echo "Python version: $(python --version)"
          echo "System: $(uname -a)"
          echo "Working directory: $(pwd)"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
